repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
        exclude: |
          (?x)(
              ^helm/|
              ^k8s/
          )
        args:
          - --multi
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
#  - repo: https://github.com/pre-commit/mirrors-eslint
#    rev: v9.20.1
#    hooks:
#      - id: eslint
