apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
spec:
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
