apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
spec:
  selector:
    app: {{ include "name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
